-- Update process_transfer function to return transaction_number
CREATE OR REPLACE FUNCTION public.process_transfer(recipient_phone_param text, amount_param numeric, note_param text DEFAULT NULL::text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  sender_user_id UUID;
  recipient_user_id UUID;
  sender_balance_record RECORD;
  transfer_id UUID;
  sender_phone_record TEXT;
  _fee_config JSONB;
  _fee_info JSONB;
  _total_deducted NUMERIC;
  _is_activated BOOLEAN;
  _current_balance NUMERIC;
  _transaction_number TEXT;
BEGIN
  -- Get current user
  sender_user_id := auth.uid();
  
  IF sender_user_id IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'User not authenticated');
  END IF;

  -- Check if sender account is activated
  SELECT is_account_activated INTO _is_activated
  FROM public.profiles
  WHERE user_id = sender_user_id;
  
  IF NOT COALESCE(_is_activated, false) THEN
    RETURN json_build_object('success', false, 'error', 'يجب تفعيل حسابك أولاً لإجراء التحويلات');
  END IF;

  -- Check rate limit: 10 transfers per hour
  IF NOT check_rate_limit(sender_user_id, 'transfer', 10, 60) THEN
    RETURN json_build_object('success', false, 'error', 'تجاوزت الحد الأقصى للتحويلات. حاول مرة أخرى لاحقاً');
  END IF;

  -- INPUT VALIDATION
  IF amount_param IS NULL OR amount_param <= 0 OR amount_param > 1000000 THEN
    RETURN json_build_object('success', false, 'error', 'Invalid amount: must be between 0.01 and 1,000,000 DZD');
  END IF;

  IF recipient_phone_param IS NULL OR recipient_phone_param !~ '^[0-9+]{10,15}$' THEN
    RETURN json_build_object('success', false, 'error', 'Invalid phone number format');
  END IF;

  IF note_param IS NOT NULL AND LENGTH(note_param) > 500 THEN
    RETURN json_build_object('success', false, 'error', 'Note too long: maximum 500 characters');
  END IF;

  -- Recalculate sender balance
  PERFORM public.recalculate_user_balance(sender_user_id);

  -- Get sender's phone
  SELECT phone INTO sender_phone_record 
  FROM public.profiles 
  WHERE user_id = sender_user_id;

  -- Find recipient by phone
  SELECT user_id INTO recipient_user_id
  FROM public.profiles 
  WHERE phone = recipient_phone_param;
  
  IF recipient_user_id IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'Recipient not found');
  END IF;

  IF sender_user_id = recipient_user_id THEN
    RETURN json_build_object('success', false, 'error', 'Cannot transfer to yourself');
  END IF;

  -- Get transfer fee configuration
  SELECT setting_value INTO _fee_config
  FROM public.platform_settings
  WHERE setting_key = 'transfer_fees';
  
  -- Calculate fees
  _fee_info := public.calculate_fee(amount_param, _fee_config);
  _total_deducted := amount_param + (_fee_info->>'fee_amount')::NUMERIC;

  -- Check sender balance
  SELECT balance INTO _current_balance
  FROM public.user_balances 
  WHERE user_id = sender_user_id;
  
  IF COALESCE(_current_balance, 0) < _total_deducted THEN
    RETURN json_build_object('success', false, 'error', 'Insufficient balance (including fees)');
  END IF;

  -- Create transfer record (transaction_number will be auto-generated by trigger)
  INSERT INTO public.transfers (sender_id, recipient_id, sender_phone, recipient_phone, amount, note)
  VALUES (sender_user_id, recipient_user_id, sender_phone_record, recipient_phone_param, amount_param, note_param)
  RETURNING id, transaction_number INTO transfer_id, _transaction_number;

  -- Record platform revenue (fees)
  PERFORM public.record_platform_revenue('transfer_fee', transfer_id, sender_user_id, _fee_info, amount_param);

  -- DON'T update user_balances directly - the trigger will call recalculate_user_balance
  -- This prevents double updates

  RETURN json_build_object(
    'success', true, 
    'transfer_id', transfer_id,
    'recipient_id', recipient_user_id,
    'transaction_number', _transaction_number,
    'fee_amount', (_fee_info->>'fee_amount')::NUMERIC,
    'total_deducted', _total_deducted
  );
END;
$$;